"""Exploratory (post-hoc) diagnostic: does left/right visual input stay separated at the
escape neurons?

NOT a pre-registered measure. It was added on 2026-09-23 after the first three control runs
all scored 0.0, to explain *why* they failed. It is reported in docs/EXPLORATORY.md, labelled
as exploratory, and never feeds the pre-registered C2 comparison in docs/RESULTS.md.

Protocol, per network (real + every control): drive only the left-side input seeds at 150 Hz
(the Shiu et al. default Poisson rate) for 1 simulated second, measure the mean firing rate of
the left-side and right-side output seeds; repeat with the right-side inputs. Then

    lateralization = ((same_L - opp_L) + (same_R - opp_R)) / (same_L + opp_L + same_R + opp_R)

where same_L is left-DN firing under left-eye drive, opp_L is right-DN firing under left-eye
drive, and so on. 1 = each side's escape neurons hear only their own eye; 0 = no separation.

Why it matters for this task: the interface (PLAN Step 5) encodes "bird above / below the gap"
as a left/right split of the input seeds, so a readout can only tell the two apart if the
network keeps the sides separate. The result is therefore conditional on that interface choice.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import scipy.sparse as sp

from flybrain.lif import Simulator, load_network

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONTROLS_DIR = PROJECT_ROOT / "data" / "derived" / "controls"
RUNS_DIR = PROJECT_ROOT / "runs"

DRIVE_HZ = 150.0
N_STEPS = 5000  # 1 simulated second at dt = 0.2 ms
N_TRIALS = 4
SEED_BASE = 1300


def lateralization(W, neurons) -> dict:
    inp = (neurons["role"] == "input_seed").to_numpy()
    side = neurons["somaSide"].to_numpy()
    out = neurons.index[neurons["role"] == "output_seed"].to_numpy()
    out_l, out_r = out[side[out] == "L"], out[side[out] == "R"]
    n = W.shape[0]

    rates = {}
    background = []
    for eye in ("L", "R"):
        sim = Simulator(W, n_candidates=N_TRIALS, dt=0.2,
                        seeds=np.arange(N_TRIALS, dtype=np.uint64) + SEED_BASE)
        drive = np.zeros((N_TRIALS, n), np.float32)
        drive[:, inp & (side == eye)] = DRIVE_HZ
        mean_hz = sim.run(N_STEPS, drive).mean(0)  # 1 s window, so counts == Hz
        rates[eye] = (float(mean_hz[out_l].mean()), float(mean_hz[out_r].mean()))
        background.append(float(mean_hz[~inp].mean()))  # every non-input neuron

    same_l, opp_l = rates["L"]
    opp_r, same_r = rates["R"]
    total = same_l + opp_l + same_r + opp_r
    li = ((same_l - opp_l) + (same_r - opp_r)) / total if total > 0 else float("nan")
    return {"left_eye": {"left_dn_hz": same_l, "right_dn_hz": opp_l},
            "right_eye": {"right_dn_hz": same_r, "left_dn_hz": opp_r},
            "lateralization": li,
            "network_hz": float(np.mean(background))}


def heldout_mean(network: str) -> list[float]:
    """Held-out means of the run(s) trained on this network, if any have finished."""
    means = []
    for f in sorted((RUNS_DIR / network).glob("seed_*/heldout.json")):
        means.append(float(json.loads(f.read_text(encoding="utf-8"))["mean"]))
    return means


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(PROJECT_ROOT / "docs" / "EXPLORATORY.md"))
    args = parser.parse_args(argv)

    W_real, neurons = load_network()
    rows = [("real", lateralization(W_real, neurons), heldout_mean("real"))]
    for path in sorted(CONTROLS_DIR.glob("control_*.npz")):
        W = sp.load_npz(path).tocsr().astype(np.float32)
        rows.append((path.stem, lateralization(W, neurons), heldout_mean(path.stem)))
        print(f"{path.stem}: {rows[-1][1]['lateralization']:.3f}", flush=True)

    real_li = rows[0][1]["lateralization"]
    ctrl_li = np.array([r[1]["lateralization"] for r in rows[1:]])
    real_hz = rows[0][1]["network_hz"]
    ctrl_hz = np.array([r[1]["network_hz"] for r in rows[1:]])
    print(f"real: {real_li:.3f} | controls: median {np.median(ctrl_li):.3f}, "
          f"max {ctrl_li.max():.3f}, n={ctrl_li.size}")

    lines = [
        "# Exploratory finding: left/right separation",
        "",
        "> **Exploratory, not pre-registered.** Added on 2026-09-23 after the first three control",
        "> runs all scored 0.0, to explain why they failed. It does not change or add to the",
        "> pre-registered comparison in [RESULTS.md](RESULTS.md). Generated by",
        "> `python -m flybrain.diagnose`; every number below comes from that script.",
        "",
        "## What was measured",
        "",
        f"Each network's left-side input (looming) neurons were driven at {DRIVE_HZ:.0f} Hz for one",
        "simulated second and the firing of the left- and right-side escape (output) neurons was",
        "recorded; then the same for the right side. The lateralization index is 1 when each",
        "side's escape neurons respond only to their own eye and 0 when they cannot tell the",
        f"eyes apart. Mean of {N_TRIALS} trials per condition.",
        "",
        "## Result",
        "",
        f"- Real connectome: **{real_li:.3f}**",
        f"- Shuffled controls (n = {ctrl_li.size}): median **{np.median(ctrl_li):.3f}**, "
        f"range {ctrl_li.min():.3f} to {ctrl_li.max():.3f}",
        "",
        "A second difference, measured in the same simulations: the shuffled networks are much",
        f"more active overall. Mean firing of all non-input neurons was {real_hz:.1f} Hz in the",
        f"real connectome and {np.median(ctrl_hz):.1f} Hz (median; range {ctrl_hz.min():.1f} to",
        f"{ctrl_hz.max():.1f}) in the shuffles, about {np.median(ctrl_hz) / real_hz:.1f} times",
        "higher. Either difference could contribute to the controls failing; this analysis",
        "cannot separate them.",
        "",
        "| network | left eye: left DN / right DN (Hz) | right eye: right DN / left DN (Hz) "
        "| lateralization | network Hz | held-out mean |",
        "|---|---|---|---|---|---|",
    ]
    for name, d, means in rows:
        held = ", ".join(f"{m:.2f}" for m in means) if name != "real" else (
            f"median {np.median(means):.2f} (n={len(means)})" if means else "—")
        if name != "real" and not means:
            held = "not finished"
        lines.append(
            f"| {name} | {d['left_eye']['left_dn_hz']:.1f} / {d['left_eye']['right_dn_hz']:.1f} "
            f"| {d['right_eye']['right_dn_hz']:.1f} / {d['right_eye']['left_dn_hz']:.1f} "
            f"| {d['lateralization']:.3f} | {d['network_hz']:.1f} | {held} |")
    lines += [
        "",
        "## How to read this",
        "",
        "The real connectome, in this model, keeps the two sides separate on the way from the looming",
        "detectors to the escape neurons. A degree-preserving shuffle keeps every neuron's number",
        "of connections and neurotransmitter but scrambles *which* neurons connect, and that",
        "removes the separation.",
        "",
        "**This explanation is conditional on the interface.** The interface encodes \"bird above",
        "or below the gap\" as a left/right split of the input neurons (PLAN Step 5 — an",
        "interface convention with no biological meaning). A task or encoding that did not need",
        "left/right separation might not favour the real wiring in the same way. The accurate",
        "claim is: the real connectome preserves left/right separation that shuffling destroys,",
        "and this task, as encoded, plausibly depends on it. That dependence was not tested",
        "directly: no shuffle that keeps each side's wiring separate was run, and the shuffles",
        "also differ in overall activity (above).",
        "",
    ]
    Path(args.out).write_bytes("\n".join(lines).encode("utf-8"))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
